name: TomoChat

description: Chat app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  email_validator: ^2.0.1
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  url_launcher: ^6.0.20
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  image_cropper: ^7.0.4
  any_link_preview: ^3.0.2
  cached_network_image: ^3.2.0
  intl_phone_number_input: ^0.7.0+2
  localstore: ^1.2.3
  photo_view: ^0.15.0

# dependency_overrides:
#   photo_view:
#     git:
#       url: https://github.com/bluefireteam/photo_view
#       ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/group_default_image.png
    - assets/images/profile_default_image.jpg
    - assets/images/logo.png
