name: TomoChat

description: Chat app 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  google_fonts: ^2.2.0
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.7
  image_picker: ^0.8.4+8
  email_validator: ^2.0.1
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  url_launcher: ^6.0.20
  contacts_service: ^0.6.3
  permission_handler: ^9.2.0
  image_cropper: ^1.5.0
  photo_view: ^0.13.0
  any_link_preview: ^2.0.6
  cached_network_image: ^3.2.0
  intl_phone_number_input: ^0.7.0+2
  localstore: ^1.2.3

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/group_default_image.png
    - assets/images/profile_default_image.jpg
    - assets/images/logo.png
